"""fix_foreign_key_nullability_in_configuration_tables

Revision ID: 0cc362e18bd4
Revises: f792da96c208
Create Date: 2025-11-24 15:55:05.353922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc362e18bd4"
down_revision: str | Sequence[str] | None = "f792da96c208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "source_extraction_profiles",
        "source_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.drop_index(op.f("idx_profiles_active"), table_name="source_extraction_profiles")
    op.drop_index(op.f("idx_profiles_source"), table_name="source_extraction_profiles")
    op.drop_constraint(
        op.f("uq_source_extraction_profiles_source_id"),
        "source_extraction_profiles",
        type_="unique",
    )
    op.alter_column(
        "source_field_definitions", "source_id", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.drop_index(op.f("idx_fields_category"), table_name="source_field_definitions")
    op.drop_index(op.f("idx_fields_source"), table_name="source_field_definitions")
    op.drop_constraint(
        op.f("uq_source_field_definitions_source_id"), "source_field_definitions", type_="unique"
    )
    op.alter_column(
        "source_normalization_rules",
        "source_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.drop_index(op.f("idx_rules_source"), table_name="source_normalization_rules")
    op.alter_column(
        "source_prompt_templates", "source_id", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.drop_index(op.f("idx_templates_source"), table_name="source_prompt_templates")
    op.drop_constraint(
        op.f("uq_source_prompt_templates_source_id"), "source_prompt_templates", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_source_prompt_templates_source_id"),
        "source_prompt_templates",
        ["source_id", "template_name", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_templates_source"),
        "source_prompt_templates",
        ["source_id", "is_active"],
        unique=False,
    )
    op.alter_column(
        "source_prompt_templates", "source_id", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.create_index(
        op.f("idx_rules_source"),
        "source_normalization_rules",
        ["source_id", "is_active"],
        unique=False,
    )
    op.alter_column(
        "source_normalization_rules",
        "source_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.create_unique_constraint(
        op.f("uq_source_field_definitions_source_id"),
        "source_field_definitions",
        ["source_id", "field_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_fields_source"), "source_field_definitions", ["source_id"], unique=False
    )
    op.create_index(
        op.f("idx_fields_category"),
        "source_field_definitions",
        ["source_id", "field_category"],
        unique=False,
    )
    op.alter_column(
        "source_field_definitions", "source_id", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.create_unique_constraint(
        op.f("uq_source_extraction_profiles_source_id"),
        "source_extraction_profiles",
        ["source_id", "profile_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_profiles_source"), "source_extraction_profiles", ["source_id"], unique=False
    )
    op.create_index(
        op.f("idx_profiles_active"),
        "source_extraction_profiles",
        ["source_id", "is_active"],
        unique=False,
    )
    op.alter_column(
        "source_extraction_profiles",
        "source_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###
